dist: xenial
language: python
python:
- '3.6'
install:
- python setup.py install
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: duanenielsen
  password:
    secure: WN8my6xIGCTiqil3Zaj5jrhBK+j6a8xIbYcIsl0M165W0elGepAGyGOOmZNotF+GAtGjrLG5KgkM3QbSOShtNt6Ni8viGcT1AXEw5kXSH+yuTe0Keo0KlGtK9oqcdNVwBc0M9lsOSmJ/66RZ/ieyA1a1r7HJn/ZgX59mbW3RamPD3s9DdXOpdDRdCZHMJZFCmhezvrYgRj1K1g786r41IV9FvL4r+nQJnscyeNK9rI27naF1Rq+tV05kBlpyYiFTJKC/wnnbcPqQ1hSEdWZeyNMqdHcxYBqxaZu1vY/zO1ZNxibdtuj708JOqUQlKvezenqJhn2kKzLUpsthCib9Jltm8aBQu7GrLpYsPSp6buOJw5tc7i0ZgHxEHZgc1elSHiBJQdLaRFRmugnDUE739Ac+qf0nU3UndIoAJUix1MXebFWdJ2Umkz7dY5qAMpYE9sXxQaG7DJxTYYDiGFd1drwt3J7pvYhKv4dRwrOiYvIi+MyMtcQl6BIeoDVjANXnHRgfeObxWt24AA+UarAdNGfwKUWPE83/KdsgPQiaPv5q0xlsxtMaV7QezOEgA0IUVPy7rRbRTjvCrKjVRehz/vBjg1db18nAEDzAazqOIBgEQgsN24uOPtJK+1Ntv/k6WeNGQ8eh6KByNnmSA3fNnEzf7rlYvLqRHer6iLOTcY0=
  on:
    tags: true
    branch: master